[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E","F","I","UP","B","SIM"]     # base + upgrades/bugbear/simplify
ignore = ["E203","E266"]                  # common with black
exclude = ["venv",".venv","build","dist"]

[tool.ruff.lint.isort]
known-first-party = ["your_pkg_name"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
mypy_path = ["src"]

